---
version: "3.8"
services:
  movies:
    image: anil1992lodhi/moviesrepo:latest
    ports:
      - 81:80
    deploy:
    
  train:
    image: anil1992lodhi/trainsrepo:latest
    ports:
      - 82:80
    deploy:
     
  dth:
    image: anil1992lodhi/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: anil1992lodhi/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
